/**
 * @module validations/branchValidation
 * @description express-validator rule chains for branch creation, updates, querying, and deletion.
 * Enforces single-user boundaries, bound constants, and rejects forbidden administrative field injections.
 */

import mongoose from 'mongoose';
import { body, param, query } from 'express-validator';
import { BRANCH_CONSTANTS } from '../utils/constants.js';

/**
 * Validation rules for creating a new physical operational branch.
 * Operational code is strictly auto-generated by the backend and forbidden from client input.
 * @constant
 * @type {import('express-validator').ValidationChain[]}
 */
export const createBranchValidation = [
  body('name')
    .trim()
    .notEmpty()
    .withMessage('Branch name is required.')
    .isLength({ min: BRANCH_CONSTANTS.NAME_MIN_LENGTH, max: BRANCH_CONSTANTS.NAME_MAX_LENGTH })
    .withMessage(`Branch name must be between ${BRANCH_CONSTANTS.NAME_MIN_LENGTH} and ${BRANCH_CONSTANTS.NAME_MAX_LENGTH} characters.`),

  // Security Invariant: branch code is auto-generated and cannot be provided by user
  body('code')
    .custom((value) => {
      if (value !== undefined) {
        throw new Error('Branch code is auto-generated by the system and cannot be manually provided.');
      }
      return true;
    }),

  body('location.city')
    .optional()
    .trim()
    .isLength({ max: BRANCH_CONSTANTS.CITY_MAX_LENGTH })
    .withMessage(`City name cannot exceed ${BRANCH_CONSTANTS.CITY_MAX_LENGTH} characters.`),

  body('location.subcity')
    .optional()
    .trim()
    .isLength({ max: BRANCH_CONSTANTS.SUBCITY_MAX_LENGTH })
    .withMessage(`Subcity cannot exceed ${BRANCH_CONSTANTS.SUBCITY_MAX_LENGTH} characters.`),

  body('location.address')
    .optional()
    .trim()
    .isLength({ max: BRANCH_CONSTANTS.ADDRESS_MAX_LENGTH })
    .withMessage(`Address cannot exceed ${BRANCH_CONSTANTS.ADDRESS_MAX_LENGTH} characters.`),

  body('managerName')
    .optional()
    .trim()
    .isLength({ max: BRANCH_CONSTANTS.MANAGER_NAME_MAX_LENGTH })
    .withMessage(`Manager name cannot exceed ${BRANCH_CONSTANTS.MANAGER_NAME_MAX_LENGTH} characters.`),

  body('contactPhone')
    .optional()
    .trim()
    .isLength({ max: BRANCH_CONSTANTS.CONTACT_PHONE_MAX_LENGTH })
    .withMessage(`Contact phone number cannot exceed ${BRANCH_CONSTANTS.CONTACT_PHONE_MAX_LENGTH} characters.`),

  // Security Invariant: reject forbidden system/administrative field injections
  body('role')
    .custom((value) => {
      if (value !== undefined) {
        throw new Error('Role assignment is strictly prohibited.');
      }
      return true;
    }),

  body('user')
    .custom((value) => {
      if (value !== undefined) {
        throw new Error('User ownership cannot be overridden in request body.');
      }
      return true;
    }),

  body('_id')
    .custom((value) => {
      if (value !== undefined) {
        throw new Error('Branch identifier cannot be manually specified.');
      }
      return true;
    }),

  body('isArchived')
    .custom((value) => {
      if (value !== undefined) {
        throw new Error('isArchived cannot be assigned directly during creation.');
      }
      return true;
    }),

  body('archivedAt')
    .custom((value) => {
      if (value !== undefined) {
        throw new Error('archivedAt cannot be assigned directly.');
      }
      return true;
    }),

  body('normalizedName')
    .custom((value) => {
      if (value !== undefined) {
        throw new Error('normalizedName cannot be manually specified.');
      }
      return true;
    }),
];

/**
 * Validation rules for updating an existing branch.
 * @constant
 * @type {import('express-validator').ValidationChain[]}
 */
export const updateBranchValidation = [
  body('name')
    .optional()
    .trim()
    .notEmpty()
    .withMessage('Branch name cannot be empty if provided.')
    .isLength({ min: BRANCH_CONSTANTS.NAME_MIN_LENGTH, max: BRANCH_CONSTANTS.NAME_MAX_LENGTH })
    .withMessage(`Branch name must be between ${BRANCH_CONSTANTS.NAME_MIN_LENGTH} and ${BRANCH_CONSTANTS.NAME_MAX_LENGTH} characters.`),

  // Security Invariant: branch code is auto-generated and immutable
  body('code')
    .custom((value) => {
      if (value !== undefined) {
        throw new Error('Branch code is auto-generated by the system and cannot be modified.');
      }
      return true;
    }),

  body('location.city')
    .optional()
    .trim()
    .isLength({ max: BRANCH_CONSTANTS.CITY_MAX_LENGTH })
    .withMessage(`City name cannot exceed ${BRANCH_CONSTANTS.CITY_MAX_LENGTH} characters.`),

  body('location.subcity')
    .optional()
    .trim()
    .isLength({ max: BRANCH_CONSTANTS.SUBCITY_MAX_LENGTH })
    .withMessage(`Subcity cannot exceed ${BRANCH_CONSTANTS.SUBCITY_MAX_LENGTH} characters.`),

  body('location.address')
    .optional()
    .trim()
    .isLength({ max: BRANCH_CONSTANTS.ADDRESS_MAX_LENGTH })
    .withMessage(`Address cannot exceed ${BRANCH_CONSTANTS.ADDRESS_MAX_LENGTH} characters.`),

  body('managerName')
    .optional()
    .trim()
    .isLength({ max: BRANCH_CONSTANTS.MANAGER_NAME_MAX_LENGTH })
    .withMessage(`Manager name cannot exceed ${BRANCH_CONSTANTS.MANAGER_NAME_MAX_LENGTH} characters.`),

  body('contactPhone')
    .optional()
    .trim()
    .isLength({ max: BRANCH_CONSTANTS.CONTACT_PHONE_MAX_LENGTH })
    .withMessage(`Contact phone number cannot exceed ${BRANCH_CONSTANTS.CONTACT_PHONE_MAX_LENGTH} characters.`),

  // Security Invariant: reject forbidden field injections
  body('role')
    .custom((value) => {
      if (value !== undefined) {
        throw new Error('Role assignment is strictly prohibited.');
      }
      return true;
    }),

  body('user')
    .custom((value) => {
      if (value !== undefined) {
        throw new Error('User ownership cannot be overridden.');
      }
      return true;
    }),

  body('_id')
    .custom((value) => {
      if (value !== undefined) {
        throw new Error('Branch identifier cannot be changed.');
      }
      return true;
    }),

  body('isArchived')
    .custom((value) => {
      if (value !== undefined) {
        throw new Error('isArchived must be modified via dedicated archive/restore endpoints.');
      }
      return true;
    }),

  body('archivedAt')
    .custom((value) => {
      if (value !== undefined) {
        throw new Error('archivedAt cannot be modified directly.');
      }
      return true;
    }),

  body('normalizedName')
    .custom((value) => {
      if (value !== undefined) {
        throw new Error('normalizedName cannot be manually specified.');
      }
      return true;
    }),
];

/**
 * Validation rules for route parameters requiring a valid branchId or operational branch code.
 * @constant
 * @type {import('express-validator').ValidationChain[]}
 */
export const branchIdParamValidation = [
  param('branchId')
    .trim()
    .notEmpty()
    .withMessage('Branch identifier is required.')
    .custom((value) => {
      const isMongoId =
        mongoose.Types.ObjectId.isValid(value) &&
        String(new mongoose.Types.ObjectId(value)) === value;
      const isCode = /^[A-Za-z0-9-]{2,20}$/.test(value);
      if (!isMongoId && !isCode) {
        throw new Error('Invalid branch identifier format. Must be a valid ID or operational branch code.');
      }
      return true;
    }),
];

export const branchIdentifierParamValidation = branchIdParamValidation;

/**
 * Validation rules for querying/listing branches with pagination and search.
 * @constant
 * @type {import('express-validator').ValidationChain[]}
 */
export const listBranchesValidation = [
  query('page')
    .optional()
    .isInt({ min: BRANCH_CONSTANTS.PAGE_LIMIT_MIN })
    .withMessage(`Page number must be a positive integer of at least ${BRANCH_CONSTANTS.PAGE_LIMIT_MIN}.`),

  query('limit')
    .optional()
    .isInt({ min: BRANCH_CONSTANTS.PAGE_LIMIT_MIN, max: BRANCH_CONSTANTS.PAGE_LIMIT_MAX })
    .withMessage(`Page limit must be between ${BRANCH_CONSTANTS.PAGE_LIMIT_MIN} and ${BRANCH_CONSTANTS.PAGE_LIMIT_MAX}.`),

  query('search')
    .optional()
    .trim()
    .isLength({ max: BRANCH_CONSTANTS.SEARCH_MAX_LENGTH })
    .withMessage(`Search query cannot exceed ${BRANCH_CONSTANTS.SEARCH_MAX_LENGTH} characters.`),

  query('archived')
    .optional()
    .customSanitizer((val) => {
      if (val === '' || val === 'true' || val === true || val === '1') return true;
      if (val === 'false' || val === false || val === '0') return false;
      return val;
    })
    .isBoolean()
    .withMessage('archived filter must be a valid boolean flag.'),

  query('isArchived')
    .optional()
    .customSanitizer((val) => {
      if (val === '' || val === 'true' || val === true || val === '1') return true;
      if (val === 'false' || val === false || val === '0') return false;
      return val;
    })
    .isBoolean()
    .withMessage('isArchived filter must be a valid boolean.'),
];

export default {
  createBranchValidation,
  updateBranchValidation,
  branchIdParamValidation,
  branchIdentifierParamValidation,
  listBranchesValidation,
};
